name: 'GitHub Actions SyncToGitee'

on:
  workflow_dispatch:
  schedule:
    - cron: '33 */3 * * *'
  watch:
    types: started
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Mirror the Github organization repos to Gitee.
        uses: Yikun/gitee-mirror-action@v0.01
        with:
          # Gitee对应的秘钥
          private_key: ${{ secrets.GITEE_KEY }}
          # 需要同步的Github组织名（源）
          github_org: lxk0301
          # 需要同步到的Gitee的组织名（目的）
          gitee_org: lxk0301