name: 'GitHub Actions SyncToGitee'

on:
  workflow_dispatch:
  schedule:
    - cron: '33 */3 * * *'
  watch:
    types: started
  push:
    branches: [ master ]
jobs:
  mirror_to_gitee:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v1
      - name: 'Mirror to Gitee'
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            git@gitee.com:lxk0301/scripts.git
          ssh_private_key:
            ${{ secrets.GITEE_KEY }}