name: 'GitHub Actions SyncToGitee'

on:
  workflow_dispatch:
  schedule:
    - cron: '33 */3 * * *'
  watch:
    types: started
  push:
    branches: [ master ]
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_KEY }}
        with:
          source-repo: "git@gitee.com:lxk0301/scripts.git"
          destination-repo: "git@gitee.com:lxk0301/scripts.git"