name: 'GitHub Actions SyncToGitee'

on:
  workflow_dispatch:
  schedule:
    - cron: '33 */3 * * *'
  watch:
    types: started
  push:
    branches: [ master ]
jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source codes
        uses: actions/checkout@v1
      - name: Mirror Github to Gitee
        uses: ./.
        with:
          src: github/lxk0301
          dst: gitee/lxk0301
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          account_type: org
          # Only sync Kunpeng
          black_list: 'crackSmartGit'
          white_list: 'scripts'
          force_update: true
          debug: true